site_name: Kubernets Deployment Platfrom
site_url: https://chrisjohn83.github.io/kubernetes-deployment-platform/
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: 01-quick-start-guide.md
  - Cluster Setup: 02-cluster-setup.md
  - Helm Charts: 03-helm-charts.md
  - CICD Pipelines: 04-cicd-pipelines.md
  - Auto Scaling: 05-autoscaling.md
  - Monitoring: 06-monitoring.md
  - Rollbacks: 07-rollbacks.md
  - Secrets Management: 08-secrets-management.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  -  pymdownx.tabbed:
       alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js