site_name: Kubernetes Deployment Platform
site_url: https://chrisjohn83.github.io/kubernetes-deployment-platform/

theme:
  name: material
  logo: assets/logo.png

  palette:
    - scheme: default
      primary: blue
      accent: cyan

    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - assets/custom.css

nav:
  - Kubernet:
      - Home: Kubernet/index.md
      - Getting Started: Kubernet/01-quick-start-guide.md
      - Cluster Setup: Kubernet/02-cluster-setup.md
      - Helm Charts: Kubernet/03-helm-charts.md
      - CICD Pipelines: Kubernet/04-cicd-pipelines.md
      - Auto Scaling: Kubernet/05-autoscaling.md
      - Monitoring: Kubernet/06-monitoring.md
      - Rollbacks: Kubernet/07-rollbacks.md
      - Secrets Management: Kubernet/08-secrets-management.md
  - Developer-onboarding:
      - Home: Developer-onboarding/index.md
      - "User Personas": Developer-onboarding/User-personas.md
      - Authentication: Developer-onboarding/Authentication.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

copyright: >
  © 2026 Kubernetes Deployment Platform |
  Documentation Prototype by Chris Johnjoseph