
name: Build and Deploy

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install mkdocs==1.6.1
          pip install mkdocs-material==9.6.14
          pip install pymdown-extensions==10.16.1
          npm install -g markdownlint-cli
          pip install vale
          cargo install lychee

      - name: Install Lychee
        run: cargo install lychee

      - name: Markdown Lint Validation
        run: |
          markdownlint docs/**/*.md README.md

      - name: Vale Spell Check
        uses: errata-ai/vale-action@reviewdog
        with:
          files: docs/

      - name: Build MkDocs Site
        run: |
          mkdocs build --strict

      - name: Broken Link Validation
        run: |
          lychee site/**/*.html

      - name: Validate MkDocs Build Strictly
        run: |
          mkdocs build --strict

  deploy:
    needs: validate

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs
        run: |
          pip install mkdocs==1.6.1
          pip install mkdocs-material==9.6.14
          pip install pymdown-extensions==10.16.1

      - name: Deploy Documentation
        run: |
          mkdocs gh-deploy --force